language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - "pip install 'coverage<4' coveralls cython"
# command to install dependencies
install: "python setup.py build_ext --inplace"
# command to run tests
script: coverage run --source=pyredblack setup.py test
after_success: coveralls
