language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - "pip install cython"
  - "cython --cplus pyredblack/redblack.pyx"
# command to install dependencies
install: "python setup.py build_ext --inplace"
# command to run tests
script: nosetests
